version: '3.1'
services:
  app:
    container_name: php_bookmedik
    build: ./build/
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - xd
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - xd
networks:
    xd:
volumes:
    mariadb_data:
